<?php
declare(strict_types=1);
/**
 * @file
 * Primary module hooks for My Node Fields module.
 */

/**
 * Implements hook_views_data_alter().
 */
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_data_alter().
 */
function custom_view_term_icon_views_data_alter(array &$data) {
  // Ensure the 'taxonomy_term_field_data' table is modified, not just 'taxonomy_term'.
  if (isset($data['taxonomy_term_field_data'])) {
    $data['taxonomy_term_field_data']['term_icon'] = [
      'title' => t('Term Icon'),
      'group' => t('Taxonomy Term'),
      'help' => t('Render term icon based on taxonomy term.'),
      'field' => [
        'id' => 'term_icon', // Must match the @ViewsField ID in the field plugin
      ],
    ];
  }

  if (isset($data['taxonomy_term_field_data'])) {
    $data['taxonomy_term_field_data']['term_icon_multi'] = [
      'title' => t('Term Icon Multi'),
      'group' => t('Taxonomy Term'),
      'help' => t('Render term icon based on taxonomy term Multi.'),
      'field' => [
        'id' => 'term_icon_multi', // Must match the @ViewsField ID in the field plugin
      ],
    ];
  }

  if (isset($data['taxonomy_term_field_data'])) {
    $data['taxonomy_term_field_data']['term_icon_extra'] = [
      'title' => t('Term Icon extra'),
      'group' => t('Taxonomy Term'),
      'help' => t('Render term icon based on taxonomy term Extra.'),
      'field' => [
        'id' => 'term_icon_extra', // Must match the @ViewsField ID in the field plugin
      ],
    ];
  }
}

/**
 * Implements hook_views_query_alter().
 */
function custom_view_term_icon_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Target the 'resources' view.
  if ($view->id() == 'events') {
    // Add the nid field with a groupby function.
    $query->addField('node_field_data', 'nid', '', ['function' => 'groupby']);
    // Group results by node ID.
    $query->addGroupBy('node_field_data.nid');
  }
}
